Cargamos las librerias

In [55]:
import pandas as pd
import numpy as np

In [56]:
train = pd.read_csv('/content/drive/My Drive/Python | Ciencia de Datos - Machine Learning/data-Titanic/train.csv') # cargamos los 
test = pd.read_csv('/content/drive/My Drive/Python | Ciencia de Datos - Machine Learning/data-Titanic/test.csv')

In [57]:
train.head(5)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [58]:
test.head(5)

   PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [59]:
# verificamos la cantidad de datos
train.shape

(891, 12)

In [60]:
test.shape

(418, 11)

In [61]:
# verificamos el tipo de datos
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [62]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [63]:
#verificamos valores faltantes
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [64]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [65]:
# verificamso la estadistica de los datos
train.describe()

       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

In [66]:
test.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

Preprocesar los datos

In [67]:
# cambiar los valores en la columna de Sexo
train['Sex'].replace(['female','male'],[0,1],inplace=True)
test['Sex'].replace(['female','male'],[0,1],inplace=True)

In [68]:
# cambiar los valores de embarque
train['Embarked'].replace(['Q','S','C'],[0,1,2],inplace=True)
test['Embarked'].replace(['Q','S','C'],[0,1,2],inplace=True)

In [69]:
# completar valores en edad
promedio = 30
train['Age'] = train['Age'].replace(np.nan, promedio)
test['Age'] = train['Age'].replace(np.nan, promedio)

In [70]:
# crear grupos de edades
bins = [0, 8, 15, 18, 25, 40, 60, 80]
nombres = ['1', '2', '3', '4', '5', '6', '7']
train['Age'] = pd.cut(train['Age'], bins, labels=nombres)
test['Age'] = pd.cut(test['Age'], bins, labels=nombres)

In [71]:
# eliminar la columna Cabina
train.drop(['Cabin'], axis=1, inplace=True)
test.drop(['Cabin'], axis=1, inplace=True)

In [72]:
# eliminar columnas que se consideran sin valor agregado
train = train.drop(['PassengerId', 'Name', 'Ticket'], axis=1)
test = test.drop(['Name', 'Ticket'], axis=1)

In [73]:
# eliminar datos faltantes
train.dropna(axis=0, how='any', inplace=True)
test.dropna(axis=0, how='any', inplace=True)

In [74]:
train.head(5)

   Survived  Pclass  Sex Age  SibSp  Parch     Fare  Embarked
0         0       3    1   4      1      0   7.2500       1.0
1         1       1    0   5      1      0  71.2833       2.0
2         1       3    0   5      0      0   7.9250       1.0
3         1       1    0   5      1      0  53.1000       1.0
4         0       3    1   5      0      0   8.0500       1.0

In [75]:
test.head(5)

   PassengerId  Pclass  Sex Age  SibSp  Parch     Fare  Embarked
0          892       3    1   4      0      0   7.8292         0
1          893       3    0   5      1      0   7.0000         1
2          894       2    1   5      0      0   9.6875         0
3          895       3    1   5      0      0   8.6625         1
4          896       3    0   5      1      1  12.2875         1

In [76]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    int64
 3   Age       889 non-null    category
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    float64
dtypes: category(1), float64(2), int64(5)
memory usage: 56.8 KB

In [77]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 417 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  417 non-null    int64
 1   Pclass       417 non-null    int64
 2   Sex          417 non-null    int64
 3   Age          417 non-null    category
 4   SibSp        417 non-null    int64
 5   Parch        417 non-null    int64
 6   Fare         417 non-null    float64
 7   Embarked     417 non-null    int64
dtypes: category(1), float64(1), int64(6)
memory usage: 26.8 KB

In [78]:
train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [79]:
test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

Algoritmos de Machine Learning

1- separar la informacion de sobrevivientes
2- separar los datos de entrenamiento y test
# algoritmos a usar
3- Regresion logistica
4- soporte de maquinas  vectores
4 Vecinos proximos

In [80]:
from sklearn.model_selection import train_test_split # split de preubas
from sklearn.linear_model import LogisticRegression # regresion logistica
from sklearn.svm import SVC # soporte de maquinas vectores
from sklearn.neighbors import KNeighborsClassifier # vecinos proximos

In [81]:
# separamos la informacion de sobrevivientes
X = np.array(train.drop(['Survived'],1))
y = np.array(train['Survived'])

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [83]:
# regresion logistica
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
Y_predict = logreg.predict(X_test)
print('Precision de la Regresion Logistica')
logreg.score(X_train,y_train)

Precision de la Regresion Logistica

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

0.8087201125175809

In [84]:
# soporte de maquinas de vectores
svc = SVC()
svc.fit(X_train,y_train)
Y_pred = svc.predict(X_test)
print('Precision de soporte de maquina de vectores')
svc.score(X_train, y_train)

Precision de soporte de maquina de vectores

0.6694796061884669

In [85]:
# vecinos proximos
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)
Y_pre = knn.predict(X_test)
print('Precision Vecinos proximos')
knn.score(X_train,y_train)

Precision Vecinos proximos

0.9324894514767933

Realizamos las predicciones con test

In [86]:
ids = test['PassengerId']

In [87]:
# regresion logistica
prediccion_logreg = logreg.predict(test.drop('PassengerId', axis=1))
salida_logreg = pd.DataFrame({'PassengerId': ids, 'Survived': prediccion_logreg})
print('Prediccion Regresion Logistica')
salida_logreg.head()

Prediccion Regresion Logistica

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         0

In [88]:
# soporte de maquinas de vectores
prediccion_svc = svc.predict(test.drop('PassengerId', axis=1))
salida_svc = pd.DataFrame({'PassengerId': ids, 'Survived': prediccion_svc})
print('Prediccion soporte de maquinas de vectores')
salida_svc.head()

Prediccion soporte de maquinas de vectores

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [89]:
# vecinos proximos
prediccion_knn = knn.predict(test.drop('PassengerId', axis=1))
salida_knn = pd.DataFrame({'PassengerId': ids, 'Survived': prediccion_knn})
print('Prediccion vecinos proximos')
salida_knn.head()

Prediccion vecinos proximos

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [90]:
salida_knn

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         1
414         1306         1
415         1307         0
416         1308         1
417         1309         1

[417 rows x 2 columns]

In [92]:
salida_logreg.to_csv('/content/drive/My Drive/Python | Ciencia de Datos - Machine Learning/data-Titanic/entrega_logreg.csv', index=False)